config/routes.rb
Rails.application.routes.draw do
  root to: "pages#landing_page"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  get '/auth/spotify', as: 'spotify_auth'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :posts do
    collection do
      get :search
    end

    resources :comments, only: %i[new create]
    resources :favorites, only: %i[create]
  end

  resources :favorites, only: [:index, :destroy]

  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#edit', as: :profile_edit

  get '/terms', to: 'pages#terms'

  get '/home', to: 'pages#home'

  resources :users, only: %i[index show edit update]

  resources :friendships, only: %i[index new create] do
    member do
      patch :accept
      patch :reject
    end
  end
end

app/views/shared/_favorite-post-link.html.erb
<%= link_to post_favorites_path(post),
            data: {
              controller: "favorite-button",
              action: "click->favorite-button#favorite",
              favorite_button_favorited_value: current_user.favorites?(post),
              favorite_button_favorite_id_value: (Favorite.find_by(user: current_user, post: post).id unless Favorite.find_by(user: current_user, post: post).nil?)
            } do %>
  <i data-favorite-button-target="icon" class="fa-<%= current_user.favorites?(post) ? 'solid' : 'regular' %> fa-heart "
    style="color: #87DB1F;"></i>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-main">
  <div class="footer-buttons">
      <%= link_to posts_path do %>
        <%= image_tag "1.png", class:"footerbar" %>
      <% end %>
      <%= link_to search_posts_path do %>
        <%= image_tag "2.png", class:"footerbar" %>
      <% end %>
      <%= link_to "", href="#" %>
        <%= image_tag "3.png", class:"footerbar" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= image_tag "favicon.png", class: "navbar-logo" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <% if user_signed_in? && current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, height: 80, width: 80, crop: :fill, class: "navbar-avatar" %>
      <% else %>
        <%= image_tag "avatar-kurt.png", class: "navbar-avatar" %>
      <% end %>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="User-Dropdown U-open">
        <li class="nav-item active"><%= link_to "My Profile", profile_path, class: "dropdown-item nav-link" %></li>
        <li class="nav-item active"><%= link_to "Liked songs", favorites_path, class: "dropdown-item nav-link" %></li>
        <li class="nav-item active"><%= link_to "My friends", friendships_path, class: "dropdown-item nav-link" %></li>
        <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"dropdown-item"%></li>
      </ul>
    </div>
  </div>
</div>