config/routes.rb
Rails.application.routes.draw do
  root to: "pages#landing_page"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  get '/auth/spotify', as: 'spotify_auth'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :posts do
    collection do
      get :search
    end

    resources :comments, only: %i[new create]
    resources :favorites, only: %i[create]
  end

  resources :favorites, only: [:index, :destroy]

  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#edit', as: :profile_edit

  get '/terms', to: 'pages#terms'

  get '/home', to: 'pages#home'

  resources :users, only: %i[index show edit update]

  resources :friendships, only: %i[index new create] do
    member do
      patch :accept
      patch :reject
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :asker, class_name: "User", foreign_key: "asker_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  validates :asker_id, presence: true
  validates :receiver_id, presence: true
  validates :asker_id, uniqueness: { scope: :receiver_id }
  validate :not_self_friending

  enum status: { requested: 1, accepted: 2, rejected: 3 }

  def not_self_friending
    if asker_id == receiver_id
      errors.add(:receiver_id, "can't be the same as asker")
    end
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :find_friendship, only: %i[edit update destroy accept reject]

  def new
    @friendship = Friendship.new
  end

  def index
    @pending_friendships = current_user.pending_friendships_received
    @accepted_friendships = current_user.accepted_friendships
  end

  def create
    @friendship = Friendship.new(friendship_params)
    @friendship.asker = current_user
    @friendship.save

    redirect_to user_friendships_path
  end

  def accept
    @friendship.accepted!

    redirect_to friendships_path
  end

  def reject
    @friendship.rejected!

    redirect_to friendships_path
  end

  private

  def friendship_params
    params.require(:friendship).permit(:receiver)
  end

  def find_friendship
    @friendship = Friendship.find(params[:id])
  end
end

app/views/friendships/index.html.erb
<div class="user-contain">
  <div class="profile-info d-flex" >
    <div class="profile-pic">
      <%= user_avatar(current_user) %>
    </div>
    <div class="info-user">
      <h2 class="profile-username">@<%= current_user.username %></h2>
      <h3 class="profile-email"><%= current_user.email %></h3>
      <h4 class="profile-bio1"><%= current_user.bio %></h4>
    </div>
  </div>

  <h1 class="prof1">Friendships</h1>
  <div class="pending-container">
    <h2 class="pending-title">Pending Requests</h2>
      <div class="all-pending d-flex flex-column gap-2 mx-4">
        <% @pending_friendships.each do |friendship| %>
          <div class="d-flex justify-content-between">
            <div class="d-flex align-items-center">
              <div class="pending-img m-0">
                <%= user_avatar(friendship.asker) %>
              </div>

              <div class="pending-info">
                <h1 class="username-pending"><%= friendship.asker.username %></h1>
              </div>
            </div>

            <div class="d-flex align-items-center">
              <%= link_to accept_friendship_path(friendship),
                data: { turbo_method: :patch }, class: 'btn-accept' do %>
                <i class="fa-regular fa-circle-check"></i>
              <% end %>

              <%= link_to reject_friendship_path(friendship),
                data: { turbo_method: :patch }, class: 'btn-reject' do %>
                <i class="fa-regular fa-circle-xmark"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
  </div>


</div>


<div class="friends">
  <h2 class="friends-title">Friends</h2>
  <div class="friend-info d-flex flex-column">
    <% @accepted_friendships.each do |friendship| %>
      <% friend = friendship.asker == current_user ? friendship.receiver : friendship.asker %>
      <div class="d-flex mb-3 w-100">
        <div class="friends-pic">
          <%= user_avatar(friend) %>
        </div>
        <div class="users-info">
          <h1 class="username-friendships"><%= friend.username %></h1>
          <h1 class="email-friendships"><%= friend.email %></h1>
        </div>
      </div>
    <% end %>
  </div>
</div>