config/routes.rb
Rails.application.routes.draw do
  root to: "pages#landing_page"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  get '/auth/spotify', as: 'spotify_auth'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :posts do
    collection do
      get :search
    end

    resources :comments, only: %i[new create]
    resources :favorites, only: %i[create]
  end

  resources :favorites, only: [:index, :destroy]

  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#edit', as: :profile_edit

  get '/terms', to: 'pages#terms'

  get '/home', to: 'pages#home'

  resources :users, only: %i[index show edit update]

  resources :friendships, only: %i[index new create] do
    member do
      patch :accept
      patch :reject
    end
  end
end

app/views/pages/_spotify_connect.html.erb
<%= link_to 'Connect to Spotify', '/auth/spotify', method: :post, class:"continue-button" %>

app/views/pages/home.html.erb
<div class="connect-page">

  <div class="logo-connect">
    <%= image_tag("logo_light.png", width: 120) %>
  </div>

  <div class="yessir">
    <div class="connect-spotify">
      <div class="status-connect"><%= user_signed_in? ? "Signed in with:  #{current_user.email}" : "Not signed in" %></div>
    </div>
  </div>

  <div class="button-spotify-connect d-flex">
    <% if user_signed_in? && current_user.provider.nil? %>
      <%= render "spotify_connect" %>
  </div>
  <div>
      <% else %>
        <%= link_to "Continue", search_posts_path, class:"continue-button"%>
    <% end %>
  </div>

  <div class="button-spotify-connect1 d-flex">
    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class:"logout-button"%>
  </div>
</div>

app/views/pages/landing_page.html.erb
<div class="logo">
  <%= image_tag "logo_light.png", class:"img-logo" %>
</div>

<div class="tree hidden">
  <div class="text-tree">
    <h2>THE <span style="color: white;">SOCIAL</span></h2>
    <h2>MEDIA APP</h2>
    <h2>TO <span style="color: white;">SHARE</span></h2>
    <h2>AND DISCOVER</h2>
    <h2><span style="color: white;">MUSIC</span> WITH</h2>
    <h2>YOUR NETWORK</h2>
    <h2>OF FRIENDS</h2>
  </div>
  <div class="words-tree">
    <h1 class="first"><strong>LISTEN. <span style="color: white;">SHARE.</span></strong></h1>
    <h1 class="second"><strong>DISCOVER.</strong></h1>
    <h1 class="third">
      <strong><span style="color: white;">CONNECT!</span></strong>
      <div class="skip">
        <% if current_user.nil? %>
          <%= link_to new_user_session_path do %>
            <i class="fa-solid fa-angles-right" style="color: white"></i>
          <% end %>
        <% else %>
          <%= link_to home_path do %>
            <i class="fa-solid fa-angles-right" style="color: white"></i>
          <% end %>
        <% end %>
      </div>
    </h1>
  </div>
</div>

<script>
  setTimeout(function() {
    var logo = document.querySelector('.logo');
    var tree = document.querySelector('.tree');
    logo.classList.add('hidden');
    tree.classList.remove("hidden");
    tree.classList.add('show-tree');
  }, 1500);
</script>

app/views/pages/test_footer.html.erb
<div class="footerbar">
  <div class="footer-img">
    <%= image_tag "footer bar.png" %>
  </div>
</div>
  <div class="footer-buttons">
      <%= link_to posts_path do %>
        <div class="home-button">
        </div>
      <% end %>
      <%= link_to search_posts_path do %>
        <div class="post-button1">
        </div>
      <% end %>
      <%= link_to "", href="#" %>
        <div class="chat-button">
        </div>
  </div>