config/routes.rb
Rails.application.routes.draw do
  root to: "pages#landing_page"
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' }

  get '/auth/spotify', as: 'spotify_auth'
  get '/auth/spotify/callback', to: 'users#spotify'

  resources :posts do
    collection do
      get :search
    end

    resources :comments, only: %i[new create]
    resources :favorites, only: %i[create]
  end

  resources :favorites, only: [:index, :destroy]

  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#edit', as: :profile_edit

  get '/terms', to: 'pages#terms'

  get '/home', to: 'pages#home'

  resources :users, only: %i[index show edit update]

  resources :friendships, only: %i[index new create] do
    member do
      patch :accept
      patch :reject
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :content, presence: true
  validates :spotify_track_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @track = Track.new(params)
  end

  def search
    @post = Post.new
    if params[:search].present?
      @tracks = RSpotify::Track.search(params[:search][:tracks])
    end
  end

  def create
    @post = Post.new(post_params)
    @track = Track.new(track_params)
    @post.user = current_user
    @post.spotify_track_id = track_params[:track_id]
    @post.album_cover_url = track_params[:track_image]

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @favorite = Favorite.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end

  def track_params
    params.require(:post).permit(:track_id, :track_image, :track_artist, :track_name, :track_album)
  end
end

app/views/posts/_new_comment_form.html.erb
<div class="new-comment" id="<%= "#{dom_id(@post)}_form" %>">
  <%= simple_form_for [post, comment] do |f| %>
    <div class="d-flex justify-content-center">
      <%= f.input :content, label: false, placeholder: "Write a comment", input_html: {maxlength: 30, size: 100} %>
      <%= f.button :submit, ">>", class: "button-comment" %>
    </div>
  <% end %>
</div>

app/views/posts/_song_modal.html.erb
<div class="modal fade" id="modal-<%= post.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div id="embed-iframe" data-uri="<%= track.uri %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="feed-container d-flex justify-content-center" data-controller="spotify">
<div class="col-10">
  <div class="opener">
    <p class="opener-text">Discover new songs from friends:</p>
  </div>
  <div class="cards-container">
    <% @posts.reverse_each do |post| %>
      <% if post.spotify_track_id %>
      <div class="card-category">
        <% track = RSpotify::Track.find(post.spotify_track_id) %>
        <div class="card-comment d-flex">
          <%= user_avatar(post.user, class: "avatar-post") %>
          <div class="card-user-info">
            <h6><strong><%= post.user.username %></strong></h6>
            <div class="post-content">
              <%= post.content %>
            </div>
          </div>
        </div>
        <div class="d-flex">
          <% if post.album_cover_url %>
            <div class="card-album-cover">
              <%= image_tag(post.album_cover_url) %>
            </div>
          <% end %>
          <div class="card-info">
            <div class="info-band">
              <p class="track-name"><strong><%= track.name %></strong></p>
              <p><%= track.artists.first.name %></p>
              <p><%= track.album.name %></p>
            </div>
              <div class="icons">
                <%= render "shared/favorite-post-link", post: post %>
                <%= link_to post_path(post) do %>
                  <i class="fa-regular fa-comment"></i>
                <% end %>
                <button type="button" class="btn btn-primary-transparent" data-bs-toggle="modal" data-bs-target="#modal-<%= post.id %>">
                  <i class="fa-solid fa-play"></i>
                </button>
                <i class="fa-brands fa-spotify"></i>
              </div>
          </div>
        </div>
      <% end %>
      </div>
    <%= render "song_modal", post: post, track: track %>
    <% end %>
  </div>
</div>
</div>


<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }
    else
      localStorage.removeItem('firstLoad');
  }
})();

</script>

app/views/posts/new.html.erb
<div class="search-page">
  <div class="instructions">
    <h1><strong><%= current_user.username %></strong></h1>
    <h3>What is the caption for this song?</h3>
  </div>

  <div class="post-components">
    <div class="tracks d-flex">
      <div class="track-art">
        <%= image_tag @track.image %>
      </div>
      <div class="track-info">
        <%= image_tag "icon-white.png", class:"logo-white" %>
        <div class="writing">
          <div class="track-name"><strong><%= @track.name %></strong></div>
          <div class="track-artist-album"><%= @track.artist %>, <%= @track.album %></div>
        </div>
      </div>
    </div>
    <br>
    <%= simple_form_for @post do |f| %>
      <%= f.input :content, wrapper_html: { style: "margin-bottom: 0px !important" },input_html: {value: "", style: "color: white; background-color: #1B1B1B"}, label: false, placeholder: "Caption", maxlength: 100 %>
      <%= f.input_field :track_id, as: :hidden, value: @track.id %>
      <%= f.input_field :track_image, as: :hidden, value: @track.image %>
      <%= f.input_field :track_name, as: :hidden, value: @track.name %>
      <%= f.input_field :track_album, as: :hidden, value: @track.album %>
      <%= f.input_field :track_artist, as: :hidden, value: @track.artist %>
      <br>
      <div class="post-buttons d-flex">
      <%= link_to "Delete", search_posts_path, method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "button-delete-post" %>
      <%= f.submit "   Post   ", class: "post-button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="search-page">

  <div class="search-part col-10">

    <h1>Hi <%= current_user.username %></h1>
    <h3>What song is on your mind?</h3>
    <%= simple_form_for :search, url: search_posts_path, method: "GET" do |f| %>
      <%= f.input :tracks, input_html: {value: "", style: "color: white; background-color: #1B1B1B; height: 50px;"}, label: false, placeholder: "Song name" %>
    <% end %>
  </div>
  <% if @tracks.present? %>

    <% @tracks.each do |track| %>

    <div class="tracks-list">

      <div class="tracks d-flex">


        <div class="track-art">
          <% url = (track.album.images[2]["url"] unless track.album.images[2]["url"].nil?) %>
          <%= image_tag "#{url}" %>
        </div>

        <div class="track-info">
          <%= image_tag "icon-white.png", class:"logo-white" %>
          <div class="writing">
            <div class="track-name"><strong><%= track.name %></strong></div>
            <div class="track-artist-album"><%= track.artists.first.name%>, <%= track.album.name %></div>
          </div>
        </div>
        <div class="select-track">
          <%= link_to new_post_path(track_id: track.id, track_image: track.album.images[2]["url"], track_name: track.name, track_artist: track.artists.first.name, track_album: track.album.name) do %>
            <i class="fa-solid fa-plus "></i>
          <% end %>
        </div>


      </div>

    </div>
    <% end %>
  <% end %>
</div>

app/views/posts/show.html.erb
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function(){
      $("#toggle-btn").click(function(){
        $("#toggle-example").collapse('toggle'); // toggle collapse
      });
    });
  </script>

<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem('firstLoad') )
    {
      localStorage['firstLoad'] = true;
      window.location.reload();
    }
    else
      localStorage.removeItem('firstLoad');
  }
})();

</script>

<br>
<br>
<div class="show-page d-flex text-start">
  <div class="user-info">
    <div class="user-call">
      <%= current_user.username %>,
    </div>
    <div class="leave-comment">
      Leave your comment here:
    </div>
  </div>

  <div class="cards-container">
    <div class="card-category">
      <% if @post.spotify_track_id %>
        <% track = RSpotify::Track.find(@post.spotify_track_id) %>

        <div class="card-comment d-flex">
            <% if user_signed_in? && current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, height: 80, width: 80, crop: :fill, class: "avatar-post" %>
            <% else %>
              <%= image_tag "avatar-kurt.png", class: "navbar-avatar" %>
            <% end %>
          <div class="card-user-info">
            <h6><strong><%= current_user.username %></strong></h6>
            <div class="post-content">
              <%= @post.content %>
            </div>
          </div>
        </div>

        <div class="d-flex">

          <% if @post.album_cover_url %>
          <div class="card-album-cover">
            <%= image_tag(@post.album_cover_url) %>
          </div>
          <% end %>

          <div class="card-info">
            <div class="info-band">
              <p class="track-name"><strong><%= track.name %></strong></p>
              <p><%= track.artists.first.name %></p>
              <p><%= track.album.name %></p>
            </div>

            <div class="icons">
              <%# <i class="fa-regular fa-heart"></i> %>
              <%= render "shared/favorite-post-link", post: @post %>
              <%= link_to post_path(@post) do %>
                <i class="fa-regular fa-comment"></i>
              <% end %>
              <button type="button" class="btn btn-primary-transparent" data-bs-toggle="modal" data-bs-target="#modal-<%= @post.id %>">
                <i class="fa-solid fa-play"></i>
              </button>
              <i class="fa-brands fa-spotify"></i>
            </div>

          </div>
        </div>

      <% end %>

    <%= render partial: "posts/song_modal", locals: { post: @post, track: track } %>


      <div class="comments-section">

        <div class="all-comments mb-3">
          <div class="commented-ones" id="toggle-btn" data-toggle="collapse" data-target="#toggle-example">
            See all comments
          </div>
          <div id="toggle-example" class="collapse">
          <ul class="ul-commentn"><% @post.comments.each do |comment| %>
              <li><span class="username-say"><%= comment.user.username %> said:</span> <span class="said"><%= comment.content %></span></li>
          <% end %></ul>
          </div>
        </div>

        <%= render partial: "posts/new_comment_form", locals: { post: @post, comment: @comment } %>

      </div>

    </div>
  </div>
</div>